import jsdocPlugin from 'eslint-plugin-jsdoc'
export default {
  ...jsdocPlugin.configs['flat/recommended-typescript-flavor'].rules,
  'jsdoc/check-access': 'off',
  'jsdoc/check-alignment': 'error',
  'jsdoc/check-examples': 'off',
  'jsdoc/check-indentation': 'error',
  'jsdoc/check-line-alignment': 'off',
  'jsdoc/check-param-names': 'error',
  'jsdoc/check-property-names': 'error',
  'jsdoc/check-syntax': 'off',
  'jsdoc/check-tag-names': 'error',
  'jsdoc/check-types': [
    'error',
    {
      unifyParentAndChildTypeChecks: true
    }
  ],
  'jsdoc/check-values': 'error',
  'jsdoc/empty-tags': 'error',
  'jsdoc/implements-on-classes': 'error',
  'jsdoc/match-description': 'off',
  'jsdoc/multiline-blocks': 'error',
  'jsdoc/no-bad-blocks': 'off',
  'jsdoc/no-defaults': 'off',
  'jsdoc/no-missing-syntax': 'off',
  'jsdoc/no-multi-asterisks': 'error',
  'jsdoc/no-restricted-syntax': 'off',
  'jsdoc/no-types': 'off',
  'jsdoc/no-undefined-types': 'error',
  'jsdoc/require-asterisk-prefix': 'off',
  'jsdoc/require-description': 'off',
  'jsdoc/require-description-complete-sentence': 'off',
  'jsdoc/require-example': 'off',
  'jsdoc/require-file-overview': 'off',
  'jsdoc/require-hyphen-before-param-description': 'off',
  'jsdoc/require-jsdoc': 'warn',
  'jsdoc/require-param': 'error',
  'jsdoc/require-param-description': 'off',
  'jsdoc/require-param-name': 'error',
  'jsdoc/require-param-type': 'error',
  'jsdoc/require-property': 'error',
  'jsdoc/require-property-description': 'off',
  'jsdoc/require-property-name': 'error',
  'jsdoc/require-property-type': 'error',
  'jsdoc/require-returns': 'error',
  'jsdoc/require-returns-check': 'error',
  'jsdoc/require-returns-description': 'off',
  'jsdoc/require-returns-type': 'error',
  'jsdoc/require-throws': 'off',
  'jsdoc/require-yields': 'error',
  'jsdoc/require-yields-check': 'error',
  'jsdoc/tag-lines': 'error',
  'jsdoc/valid-types': 'warn'
}
