declare const _default: {
    'jsdoc/check-access': string;
    'jsdoc/check-alignment': string;
    'jsdoc/check-examples': string;
    'jsdoc/check-indentation': string;
    'jsdoc/check-line-alignment': string;
    'jsdoc/check-param-names': string;
    'jsdoc/check-property-names': string;
    'jsdoc/check-syntax': string;
    'jsdoc/check-tag-names': string;
    'jsdoc/check-types': (string | {
        unifyParentAndChildTypeChecks: boolean;
    })[];
    'jsdoc/check-values': string;
    'jsdoc/empty-tags': string;
    'jsdoc/implements-on-classes': string;
    'jsdoc/match-description': string;
    'jsdoc/multiline-blocks': string;
    'jsdoc/no-bad-blocks': string;
    'jsdoc/no-defaults': string;
    'jsdoc/no-missing-syntax': string;
    'jsdoc/no-multi-asterisks': string;
    'jsdoc/no-restricted-syntax': string;
    'jsdoc/no-types': string;
    'jsdoc/no-undefined-types': string;
    'jsdoc/require-asterisk-prefix': string;
    'jsdoc/require-description': string;
    'jsdoc/require-description-complete-sentence': string;
    'jsdoc/require-example': string;
    'jsdoc/require-file-overview': string;
    'jsdoc/require-hyphen-before-param-description': string;
    'jsdoc/require-jsdoc': string;
    'jsdoc/require-param': string;
    'jsdoc/require-param-description': string;
    'jsdoc/require-param-name': string;
    'jsdoc/require-param-type': string;
    'jsdoc/require-property': string;
    'jsdoc/require-property-description': string;
    'jsdoc/require-property-name': string;
    'jsdoc/require-property-type': string;
    'jsdoc/require-returns': string;
    'jsdoc/require-returns-check': string;
    'jsdoc/require-returns-description': string;
    'jsdoc/require-returns-type': string;
    'jsdoc/require-throws': string;
    'jsdoc/require-yields': string;
    'jsdoc/require-yields-check': string;
    'jsdoc/tag-lines': string;
    'jsdoc/valid-types': string;
};
export default _default;
